"""initial schema

Revision ID: 30745a3e0f17
Revises: 
Create Date: 2026-08-07 01:18:54.691935
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '30745a3e0f17'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('sizes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('alt', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('caption', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('region_name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_headquarters', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Enum('PRODUCT', 'POST', 'CASE_STUDY', 'SCENARIO', 'DOWNLOAD', 'PAGE', name='sourcetype', native_enum=False, length=32), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('url_path', sa.String(length=1000), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('simple', coalesce(title, '')), 'A') || setweight(to_tsvector('simple', coalesce(content, '')), 'B')", persisted=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_search_documents_fts', 'search_documents', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_search_documents_locale'), 'search_documents', ['locale'], unique=False)
    op.create_index('ix_search_documents_source', 'search_documents', ['source_type', 'source_id', 'locale'], unique=True)
    op.create_index(op.f('ix_search_documents_source_id'), 'search_documents', ['source_id'], unique=False)
    op.create_index(op.f('ix_search_documents_source_type'), 'search_documents', ['source_type'], unique=False)
    op.create_index('ix_search_documents_title_trgm', 'search_documents', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_table('service_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_address', sa.Text(), nullable=False),
    sa.Column('project_size', sa.String(length=120), nullable=True),
    sa.Column('fault_description', sa.Text(), nullable=False),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('contact_number', sa.String(length=60), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='servicerequeststatus', native_enum=False, length=20), nullable=False),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_requests_contact_email'), 'service_requests', ['contact_email'], unique=False)
    op.create_index(op.f('ix_service_requests_status'), 'service_requests', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'EDITOR', 'SALES', name='userrole', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('case_studies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('city', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('country', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('capacity_value', sa.Float(), nullable=True),
    sa.Column('capacity_unit', sa.String(length=8), nullable=True),
    sa.Column('capacity_kw', sa.Float(), nullable=True),
    sa.Column('system_type', sa.Enum('RESIDENTIAL', 'COMMERCIAL', 'UTILITY', name='systemtype', native_enum=False, length=20), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('cover_image_id', sa.UUID(), nullable=True),
    sa.Column('gallery', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seo_title', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('seo_description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('no_index', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cover_image_id'], ['media.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_studies_capacity_kw'), 'case_studies', ['capacity_kw'], unique=False)
    op.create_index(op.f('ix_case_studies_featured'), 'case_studies', ['featured'], unique=False)
    op.create_index(op.f('ix_case_studies_is_published'), 'case_studies', ['is_published'], unique=False)
    op.create_index(op.f('ix_case_studies_slug'), 'case_studies', ['slug'], unique=True)
    op.create_index(op.f('ix_case_studies_system_type'), 'case_studies', ['system_type'], unique=False)
    op.create_index(op.f('ix_case_studies_year'), 'case_studies', ['year'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('banner_image_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['banner_image_id'], ['media.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('certifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('issuing_body', sa.String(length=200), nullable=True),
    sa.Column('certificate_number', sa.String(length=200), nullable=True),
    sa.Column('issued_year', sa.Integer(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_id', sa.UUID(), nullable=True),
    sa.Column('show_on_honors_page', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['media.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('milestones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('title', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['media.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milestones_year'), 'milestones', ['year'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('excerpt', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('category', sa.Enum('COMPANY_NEWS', 'INDUSTRY_NEWS', 'EXHIBITIONS', name='postcategory', native_enum=False, length=32), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=80)), nullable=True),
    sa.Column('cover_image_id', sa.UUID(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seo_title', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('seo_description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('no_index', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cover_image_id'], ['media.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_category'), 'posts', ['category'], unique=False)
    op.create_index(op.f('ix_posts_featured'), 'posts', ['featured'], unique=False)
    op.create_index(op.f('ix_posts_is_published'), 'posts', ['is_published'], unique=False)
    op.create_index(op.f('ix_posts_slug'), 'posts', ['slug'], unique=True)
    op.create_table('scenarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('intro', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('benefits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('hero_image_id', sa.UUID(), nullable=True),
    sa.Column('system_diagram_id', sa.UUID(), nullable=True),
    sa.Column('gallery', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seo_title', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('seo_description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('no_index', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['hero_image_id'], ['media.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['scenarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['system_diagram_id'], ['media.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_is_published'), 'scenarios', ['is_published'], unique=False)
    op.create_index(op.f('ix_scenarios_parent_id'), 'scenarios', ['parent_id'], unique=False)
    op.create_index(op.f('ix_scenarios_slug'), 'scenarios', ['slug'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_number', sa.String(length=160), nullable=False),
    sa.Column('short_description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('product_type', sa.Enum('MONO_FACIAL', 'BIFACIAL', 'INVERTER', 'BATTERY', 'STORAGE_CABINET', name='producttype', native_enum=False, length=32), nullable=True),
    sa.Column('hero_image_id', sa.UUID(), nullable=True),
    sa.Column('gallery', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cell_technology', sa.Enum('N_TYPE', 'HJT_TYPE', 'BC', 'P_TYPE', name='celltechnology', native_enum=False, length=32), nullable=True),
    sa.Column('power_min', sa.Integer(), nullable=True),
    sa.Column('power_max', sa.Integer(), nullable=True),
    sa.Column('max_efficiency', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('power_tolerance', sa.String(length=60), nullable=True),
    sa.Column('annual_degradation', sa.String(length=60), nullable=True),
    sa.Column('mechanical_load_positive', sa.Integer(), nullable=True),
    sa.Column('mechanical_load_negative', sa.Integer(), nullable=True),
    sa.Column('warranty_product_years', sa.Integer(), nullable=True),
    sa.Column('warranty_power_years', sa.Integer(), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('spec_groups', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('datasheet_id', sa.UUID(), nullable=True),
    sa.Column('installation_manual_id', sa.UUID(), nullable=True),
    sa.Column('warranty_document_id', sa.UUID(), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seo_title', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('seo_description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('no_index', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['datasheet_id'], ['media.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hero_image_id'], ['media.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['installation_manual_id'], ['media.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warranty_document_id'], ['media.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_cell_technology'), 'products', ['cell_technology'], unique=False)
    op.create_index(op.f('ix_products_featured'), 'products', ['featured'], unique=False)
    op.create_index(op.f('ix_products_is_published'), 'products', ['is_published'], unique=False)
    op.create_index(op.f('ix_products_max_efficiency'), 'products', ['max_efficiency'], unique=False)
    op.create_index(op.f('ix_products_model_number'), 'products', ['model_number'], unique=False)
    op.create_index(op.f('ix_products_power_max'), 'products', ['power_max'], unique=False)
    op.create_index(op.f('ix_products_power_min'), 'products', ['power_min'], unique=False)
    op.create_index(op.f('ix_products_product_type'), 'products', ['product_type'], unique=False)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.create_table('scenario_cases',
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case_studies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scenario_id', 'case_id')
    )
    op.create_table('case_products',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case_studies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id', 'product_id')
    )
    op.create_table('downloads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('category', sa.Enum('DATASHEET', 'COMPANY', 'CERTIFICATE', 'WARRANTY', 'INSTALLATION', 'STORED_ENERGY', 'REGIONAL', name='downloadcategory', native_enum=False, length=32), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('thumbnail_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['media.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thumbnail_id'], ['media.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_downloads_category'), 'downloads', ['category'], unique=False)
    op.create_index(op.f('ix_downloads_is_published'), 'downloads', ['is_published'], unique=False)
    op.create_index(op.f('ix_downloads_region'), 'downloads', ['region'], unique=False)
    op.create_table('inquiries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=60), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.Enum('PRODUCT_PAGE', 'CONTACT_PAGE', 'CHATBOT', 'QUOTE_CALCULATOR', name='leadsource', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'QUALIFIED', 'WON', 'LOST', name='leadstatus', native_enum=False, length=20), nullable=False),
    sa.Column('page_url', sa.String(length=1000), nullable=True),
    sa.Column('referrer', sa.String(length=1000), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=True),
    sa.Column('ip_address', sa.String(length=60), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inquiries_email'), 'inquiries', ['email'], unique=False)
    op.create_index(op.f('ix_inquiries_product_id'), 'inquiries', ['product_id'], unique=False)
    op.create_index(op.f('ix_inquiries_source'), 'inquiries', ['source'], unique=False)
    op.create_index(op.f('ix_inquiries_status'), 'inquiries', ['status'], unique=False)
    op.create_table('product_certifications',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('certification_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['certification_id'], ['certifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'certification_id')
    )
    op.create_table('product_related',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('related_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'related_id')
    )
    op.create_table('product_scenarios',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'scenario_id')
    )
    op.create_table('scenario_products',
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scenario_id', 'product_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenario_products')
    op.drop_table('product_scenarios')
    op.drop_table('product_related')
    op.drop_table('product_certifications')
    op.drop_index(op.f('ix_inquiries_status'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_source'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_product_id'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_email'), table_name='inquiries')
    op.drop_table('inquiries')
    op.drop_index(op.f('ix_downloads_region'), table_name='downloads')
    op.drop_index(op.f('ix_downloads_is_published'), table_name='downloads')
    op.drop_index(op.f('ix_downloads_category'), table_name='downloads')
    op.drop_table('downloads')
    op.drop_table('case_products')
    op.drop_table('scenario_cases')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_product_type'), table_name='products')
    op.drop_index(op.f('ix_products_power_min'), table_name='products')
    op.drop_index(op.f('ix_products_power_max'), table_name='products')
    op.drop_index(op.f('ix_products_model_number'), table_name='products')
    op.drop_index(op.f('ix_products_max_efficiency'), table_name='products')
    op.drop_index(op.f('ix_products_is_published'), table_name='products')
    op.drop_index(op.f('ix_products_featured'), table_name='products')
    op.drop_index(op.f('ix_products_cell_technology'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_scenarios_slug'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_parent_id'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_is_published'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_posts_slug'), table_name='posts')
    op.drop_index(op.f('ix_posts_is_published'), table_name='posts')
    op.drop_index(op.f('ix_posts_featured'), table_name='posts')
    op.drop_index(op.f('ix_posts_category'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_milestones_year'), table_name='milestones')
    op.drop_table('milestones')
    op.drop_table('certifications')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_case_studies_year'), table_name='case_studies')
    op.drop_index(op.f('ix_case_studies_system_type'), table_name='case_studies')
    op.drop_index(op.f('ix_case_studies_slug'), table_name='case_studies')
    op.drop_index(op.f('ix_case_studies_is_published'), table_name='case_studies')
    op.drop_index(op.f('ix_case_studies_featured'), table_name='case_studies')
    op.drop_index(op.f('ix_case_studies_capacity_kw'), table_name='case_studies')
    op.drop_table('case_studies')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_service_requests_status'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_contact_email'), table_name='service_requests')
    op.drop_table('service_requests')
    op.drop_index('ix_search_documents_title_trgm', table_name='search_documents', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_search_documents_source_type'), table_name='search_documents')
    op.drop_index(op.f('ix_search_documents_source_id'), table_name='search_documents')
    op.drop_index('ix_search_documents_source', table_name='search_documents')
    op.drop_index(op.f('ix_search_documents_locale'), table_name='search_documents')
    op.drop_index('ix_search_documents_fts', table_name='search_documents', postgresql_using='gin')
    op.drop_table('search_documents')
    op.drop_table('offices')
    op.drop_table('media')
    # ### end Alembic commands ###
